-- =====================================================
-- Insurance Claims Data Warehouse
-- 01 - Snowflake Environment Setup
-- =====================================================

CREATE WAREHOUSE IF NOT EXISTS INSURANCE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS INSURANCE1_DW;

CREATE SCHEMA IF NOT EXISTS INSURANCE1_DW.RAW;
CREATE SCHEMA IF NOT EXISTS INSURANCE1_DW.STAGING;
CREATE SCHEMA IF NOT EXISTS INSURANCE1_DW.ANALYTICS;

USE WAREHOUSE INSURANCE_WH;
USE DATABASE INSURANCE1_DW;